apiVersion: v1
kind: ConfigMap
metadata:
  name: formio-config
  namespace: core
data:
  DEBUG: "formio:*"
  NODE_CONFIG: '{"mongo": "mongodb://mongo.mongo.svc.cluster.local:27017/formio"}'
  ROOT_EMAIL: "admin@example.com"
  ROOT_PASSWORD: "CHANGEME"